### ISSUE TITLE
Add support for CocoaPods "use_frameworks!".

### ISSUE THREAD

**Issue by toddfreese** [jjxtra/DRColorPicker#10]
Currently DRColorPicker will not work if you are using use_frameworks! in your pod file.

I think this is because DRColorPicker.m's DRCPTR function is using [NSBundle mainBundle] instead of bundleForClass: as per this issue: 

https://github.com/CocoaPods/CocoaPods/issues/3226

**Comment by jjxtra** [comment]
Thanks for the notification. Happy to have someone submit a pull request if they want to fix it.

**Comment by jjxtra** [comment]
Was fixed a while ago
