### ISSUE TITLE
Navigation title disappear and don't appear.

### ISSUE THREAD

**Issue by NorbertSzydlowski** [jjxtra/DRColorPicker#2]
Hi,

when I push controller navigation title disappear.

After dismiss it isn't assigned to navigation.titleview.

```
vc.rootViewController.dismissBlock = ^(BOOL cancel) {
        [self dismissViewControllerAnimated:YES completion:^{
            self.navigationItem.titleView = self.csNavigationBar; //don't work and navbar is clear
            
        }];
    };
```

**Comment by jjxtra** [comment]
Greetings,

Sorry for the late response. Is vc your own view controller or is it the color picker? What is "self" - is that your own view controller? Is it a UINavigationController or UIViewController?

**Comment by jjxtra** [comment]
I'll probably need more explanation and code to even begin to investigate this.

**Comment by jjxtra** [comment]
If you still want help with this, email me at jjxtra AT gmail DOT com and we can resolve it that way. Thanks!
