### ISSUE TITLE
How to disable import/custom photo feature?

### ISSUE THREAD

**Issue by edwinfinch** [jjxtra/DRColorPicker#3]
Hey mate,

Love the library, adding it to the iOS app for the Lignite Collection. However, I do not need the feature of being able to add your own image in. I've disabled the handling of this and it just says feature not supported, but I don't want a user to be able to touch it at all. I didn't want to go digging into the pod files, so I was wondering if there's another solution. 

Thanks!

**Comment by edwinfinch** [comment]
Nevermind, found it quickly by changing vc.rootViewController.importBlock to nil! Thanks and sorry for wasting your time.

**Comment by jjxtra** [comment]
Glad you got it sorted!

- Jeff

**Comment by khunshan** [comment]
Is there any flag of it in REQUIRED or OPTIONAL settings for DRColorPicker? Thanks
