### ISSUE TITLE
Assertion failure for hexString length #FF0000FF

### ISSUE THREAD

**Issue by jainpiyushb** [jjxtra/DRColorPicker#4]
Getting this assertion failure 
Assertion failed: (7 == hexString.length || 4 == hexString.length), function +[UIColor(HexColorAddition) colorWithHexString:alpha:], < ..... >

I have given a color as Red with designated initializer. 

Any idea why ?

**Comment by jainpiyushb** [comment]
Sorry, this problem is because of a Category used on UIColor. Didn't spot it in the first place.

**Comment by jjxtra** [comment]
Thanks. I wish objective-c would compile error on category collisions...
