### ISSUE TITLE
Storyboard version.

### ISSUE THREAD

**Issue by daviddelmonte** [jjxtra/DRColorPicker#6]
I like this control a lot. But to integrate it into my app, I'd like to integrate it into a storyboard. Then I'd like to open it as a popover. I don't want to tread all over your code, can you suggest a place to start? Many thanks

**Comment by jjxtra** [comment]
Feel free to fork the library and submit a pull request if you'd like.

Opening as a popover should be trivial. DRColorPickerViewController is the root view controller and doesn't really care how it's presented, so you can set it up as a popover if you want.

May I ask what the motivation is for using a storyboard? The user interface here is pretty simple, and mostly contains navigation bars, collection views, toolbars and a few buttons.

**Comment by daviddelmonte** [comment]
Thanks for the fast reply. If I present the control as is, it will be a different method to close the window, (bar button), than other elements that are all popovers -- a child can close the window by tapping outside of it.. I hope this makes sense, I'm jet-lagged.

**Comment by jjxtra** [comment]
You can use (BOOL)popoverControllerShouldDismissPopover:(UIPopoverController *)popoverController

**Comment by jjxtra** [comment]
UIPopoverPresentationControllerDelegate has popoverPresentationControllerShouldDismissPopover which you can return NO unless they have tapped a specific dismiss button first in which case you can return YES. Just set the delegate on UIPopoverPresentationController.

**Comment by daviddelmonte** [comment]
Hi, I have all my popovers working ok with UIPopoverPresentationController. I'm scratching my head on how to have DRColorPicker to a popover. When I call the control from a sb, I get a black screen (theme 2). I must be missing something dumb..
