### ISSUE TITLE
Integrate into Swift?

### ISSUE THREAD

**Issue by daviddelmonte** [jjxtra/DRColorPicker#9]
HOw best to integrate this (amazing) control into a swift app? THe source is fine with a bridging header, but It looks like I have to rewrite the demo view controller. Is this the best approach? THx

**Comment by jjxtra** [comment]
Can you bridge in the demo view controller also?

**Comment by daviddelmonte** [comment]
Yes, but I want to jump from my main controller directly to the picker.. I'll see if I can adjust my approach. (I was hoping you'd say-- no problem Dave, I'll write this all again in Swift for you.).. ;)

**Comment by jjxtra** [comment]
Hehehe. Apple just needs the converter written and we are good ;)
